# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Test Country Service

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]
    
    env:
      GO_PRIVATE: "github.com/revotech-group"
      TESTCONTAINER_DOCKER_NETWORK: revotech-testcontainers
      DOCKER_BUILDKIT: 1
      
    steps:
      - uses: actions/checkout@v4

      - name: Create Docker network for running Testcontianers
        run: docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }}

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Go Service Dependencies
        run: |
          git config --global url."https://${{ secrets.TOKEN }}@github.com/".insteadOf "https://github.com/"
          go env -w GOPRIVATE="${{env.GO_PRIVATE}}"
          go mod tidy
    
      - name: Test Service
        run: |
          echo "Running tests..."
          go test -v ./...

    
          